include(vcpkg_common_functions)

file(READ "${VCPKG_ROOT_DIR}/_env/EXTERNAL_NLOHMANN_JSON_JSONHPP_URLS.txt" EXTERNAL_NLOHMANN_JSON_JSONHPP_URLS)
file(READ "${VCPKG_ROOT_DIR}/_env/EXTERNAL_NLOHMANN_JSON_LICENSE_URLS.txt" EXTERNAL_NLOHMANN_JSON_LICENSE_URLS)
file(READ "${VCPKG_ROOT_DIR}/_env/EXTERNAL_NLOHMANN_JSON_JSONHPP_SHA512.txt" EXTERNAL_NLOHMANN_JSON_JSONHPP_SHA512)
file(READ "${VCPKG_ROOT_DIR}/_env/EXTERNAL_NLOHMANN_JSON_LICENSE_SHA512.txt" EXTERNAL_NLOHMANN_JSON_LICENSE_SHA512)

vcpkg_download_distfile(HEADER
    URLS ${EXTERNAL_NLOHMANN_JSON_JSONHPP_URLS}
    FILENAME "nlohmann-json.hpp"
    SHA512 ${EXTERNAL_NLOHMANN_JSON_JSONHPP_SHA512}
)

vcpkg_download_distfile(LICENSE
    URLS ${EXTERNAL_NLOHMANN_JSON_LICENSE_URLS}
    FILENAME "nlohmann-json-LICENSE.txt"
    SHA512 ${EXTERNAL_NLOHMANN_JSON_LICENSE_SHA512}
)

file(INSTALL ${HEADER} DESTINATION ${CURRENT_PACKAGES_DIR}/include/nlohmann RENAME json.hpp)
file(INSTALL ${LICENSE} DESTINATION ${CURRENT_PACKAGES_DIR}/share/nlohmann-json RENAME copyright)
