<template>
    <div>
        <!-- METAVERSE ACCOUNT SECTION/CARD -->
        <q-card class="my-card">
            <q-card-section>
                <!-- SAVE BUTTON (FOR TESTING) IGNORE FOR NOW  <q-btn @click="saveSettings" class="q-mb-sm" padding="0.5em 1.5em" push color="positive" label="save" /> -->
                <div class="text-h5 text-center text-weight-bold">Your Metaverse Account</div>
                <div v-if="isUserConnected" class="text-overline text-positive text-center">Metaverse Account Connected</div>
                <div v-else class="text-overline text-negative text-center">Account Not Connected</div>
                <!-- METAVERSE CONNECT/DISCONNECT BUTTON -->
                <q-card-actions align="center">
                    <q-btn v-if="!isUserConnected" @click="onConnectAccount" class="q-mb-sm" padding="0.5em 2em" push color="positive" label="Connect Metaverse Account" />
                    <q-btn v-else @click="confirmDisconnect=true" class="q-mb-sm" padding="0.5em 1.5em" push color="negative" label="Disconnect Account" />
                    <q-dialog v-model="confirmDisconnect" persistent>
                        <q-card class="bg-primary q-pa-sm">
                            <q-card-section class="row items-center">
                                <q-icon class="q-mb-sm q-mr-sm" name="warning" color="warning" size="1.5rem"/>
                                <span class="text-h5 q-mb-sm text-bold text-warning">Are you sure?</span>
                                <span class="text-body2">This will remove your domain-server OAuth access token.<br/>
                                This could cause your domain to appear offline and no longer be reachable via any place names.</span>
                            </q-card-section>

                            <q-card-actions align="center">
                                <q-btn flat label="Cancel" color="white" v-close-popup />
                                <q-btn @click="onConnectAccount" flat label="Confirm" color="white" v-close-popup />
                            </q-card-actions>
                        </q-card>
                    </q-dialog>
                </q-card-actions>
                <!-- *END* METAVERSE CONNECT/DISCONNECT BUTTON *END* -->
                <q-separator />
                <!-- ADVANCED SETTINGS SECTION -->
                <q-expansion-item v-model="isMetaverseSettingsToggled" class="q-mt-md text-subtitle1" popup icon="settings" label="Advanced Settings">
                    <q-card>
                        <!-- access token section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="accessToken" label="Access Token"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is your OAuth access token to connect this domain-server with your Metaverse account. It can be generated by clicking the 'Connect Account' button above.<br/>
                            You can also go to the Security page of your account on your Metaverse Server and generate a token with the 'domains' scope and paste it here.</div>
                        </q-card-section>
                        <!-- domain ID section -->
                        <q-card-section v-if="isUserConnected">
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="domainID" label="Domain ID"/>
                            <q-btn class="q-mt-xs" color="primary" label="new domain ID" />
                            <q-btn class="q-mt-xs q-ml-xs" color="primary" label="choose from my domains" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is your Metaverse domain ID. If you do not want your domain to be registered in the Metaverse you can leave this blank.</div>
                        </q-card-section>
                        <!-- local UDP port section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="localUDPPort" label="Local UDP Port"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is the local port your domain-server binds to for UDP connections.
                            Depending on your router, this may need to be changed to unique values for each domain-server in order to run multiple full automatic networking domain-servers in the same network.<br/>
                            You can use the value 0 to have the domain-server select a random port, which will help in preventing port collisions.</div>
                        </q-card-section>
                        <!-- enable packet verification section -->
                        <q-card-section>
                            <q-toggle v-model="isPacketVerificationEnabled" checked-icon="check" color="positive" label="Enable Packet Verification"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Enable secure checksums on communication that uses the Metaverse protocol. Increases security with possibly a small performance penalty</div>
                        </q-card-section>
                        <!-- enable metadata HTTP availability section -->
                        <q-card-section>
                            <q-toggle v-model="isHTTPMetadataEnabled" checked-icon="check" color="positive" label="Enable Metadata HTTP Availability"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Allows your domain's metadata to be accessible on the public internet via direct HTTP connection to the domain server</div>
                        </q-card-section>
                        <!-- metadata exporter HTTP port section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="metadataExporterPort" label="Metadata Exporter HTTP Port"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is the port where the Metaverse exporter accepts connections. It listens both on IPv4 and IPv6 and can be accessed remotely, so you should make sure to restrict access with a firewall as needed.</div>
                        </q-card-section>
                    </q-card>
                </q-expansion-item>
                <!-- *END* ADVANCED SETTINGS SECTION *END* -->
            </q-card-section>
        </q-card>
        <!-- *END* METAVERSE ACCOUNT SECTION/CARD *END* -->
    </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Settings } from "@Modules/domain/settings";
import { Description } from "@/src/modules/domain/interfaces/settings";

export default defineComponent({
    name: "MetaverseSettings",

    data () {
        return {
            descriptions: [] as Description[],
            isMetaverseSettingsToggled: false,
            confirmDisconnect: false,
            // Metaverse Account section variables
            isUserConnected: false, // TODO: get connection status
            accessToken: "" as string, // TODO: get access token
            domainID: "" as string, // TODO: get domain ID
            localUDPPort: "" as string, // TODO: get local UDP port
            isPacketVerificationEnabled: false, // TODO: get packet verification setting state
            isHTTPMetadataEnabled: false, // TODO: get metadata HTTP availability setting state
            metadataExporterPort: "" as string // TODO: get metadata exporter HTTP port
        };
    },
    methods: {
        onConnectAccount (): void {
            this.isUserConnected = !this.isUserConnected;
        },
        onDisconnectAccount (): void {
            this.isUserConnected = !this.isUserConnected;
        },
        onNewDomainID (): void {
            console.log("new domain ID");
        },
        onChooseFromDomains (): void {
            console.log("choose from domains");
        },
        async refreshSettingsValues (): Promise<void> {
            const settingsValues = await Settings.getValues();
            // assigns values and checks they are not undefined
            this.accessToken = settingsValues.metaverse?.access_token ?? "";
            this.isUserConnected = Boolean(this.accessToken); // type cast to boolean (will evaluate false if access token is empty string)
            this.domainID = settingsValues.metaverse?.id ?? "test123 (ID not found)";
            this.localUDPPort = settingsValues.metaverse?.local_port ?? "test123 (local UDP port not found)";
            this.isPacketVerificationEnabled = settingsValues.metaverse?.enable_packet_verification ?? false;
            this.isHTTPMetadataEnabled = settingsValues.metaverse?.enable_metadata_exporter ?? false;
            this.metadataExporterPort = settingsValues.metaverse?.metadata_exporter_port ?? "not found";
        },
        async getDescriptions (): Promise<void> {
            this.descriptions = await Settings.getDescriptions();
        },
        saveSettings (): void {
            const settingsToCommit = {
                "metaverse": {
                    "access_token": this.accessToken,
                    "enable_metadata_exporter": this.isHTTPMetadataEnabled,
                    "enable_packet_verification": this.isPacketVerificationEnabled,
                    "id": this.domainID,
                    "local_port": this.localUDPPort,
                    "metadata_exporter_port": this.metadataExporterPort
                }
            };
            Settings.commitSettings(settingsToCommit);
        }
    },
    beforeMount () {
        this.refreshSettingsValues();
        this.getDescriptions();
    }
});
</script>
