macro(TARGET_DRACO)
    if (ANDROID)
        set(INSTALL_DIR ${HIFI_ANDROID_PRECOMPILED}/draco)
        set(DRACO_INCLUDE_DIRS "${INSTALL_DIR}/include" CACHE TYPE INTERNAL)

        set(LIB_DIR ${INSTALL_DIR}/lib)
        list(APPEND DRACO_LIBRARIES ${LIB_DIR}/libdraco.a)
        list(APPEND DRACO_LIBRARIES ${LIB_DIR}/libdracodec.a)
        list(APPEND DRACO_LIBRARIES ${LIB_DIR}/libdracoenc.a)
    else()
        add_dependency_external_projects(draco)
        find_package(Draco REQUIRED)
        list(APPEND DRACO_LIBRARIES ${DRACO_LIBRARY})
        list(APPEND DRACO_LIBRARIES ${DRACO_ENCODER_LIBRARY})
    endif()
    target_include_directories(${TARGET_NAME} SYSTEM PRIVATE ${DRACO_INCLUDE_DIRS})
    target_link_libraries(${TARGET_NAME} ${DRACO_LIBRARIES})
endmacro()
