#!/bin/sh

ATHENA=`realpath ../..`
GITDATE=`git log -n 1 --format=raw | grep author | cut -d' ' -f 4 | xargs -I {} date -d @{} +"%Y%m%d"`
GITCOMMIT=`git rev-parse HEAD | cut -c 1-7`
VERSION=0.86.0_K1_${GITDATE}_${GITCOMMIT}

DEPENDS=mesa-libGL,`ls \
		$ATHENA/build/assignment-client/assignment-client \
		$ATHENA/build/domain-server/domain-server \
		$ATHENA/build/tools/oven/oven \
		$ATHENA/qt5-install/lib/libQt5Network.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5Core.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5Widgets.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5Gui.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5Script.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5Quick.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5WebSockets.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5Qml.so.*.*.* \
		$ATHENA/qt5-install/lib/libQt5ScriptTools.so.*.*.* \
		$ATHENA/build/ext/makefiles/quazip/project/lib/libquazip5.so.*.*.* \
		$ATHENA/build/assignment-client/plugins/*.so \
		$ATHENA/build/assignment-client/plugins/*/*.so \
	| xargs -I {} sh -c 'objdump -p {} | grep NEEDED' \
	| awk '{print $2}' \
	| sort | uniq \
	| grep -v ^libQt5 | grep -v ^libquazip | grep -v ^libGL \
	| xargs -I {} sh -c "ldconfig -p | grep {} | tr ' ' '\n' | grep /" \
	| xargs rpm -qf --queryformat "%{NAME}\n" \
	| sort | uniq \
	| paste -d',' -s`

sudo yum install chrpath

export VERSION DEPENDS ATHENA
rpmbuild --target x86_64 -bb ./athena-server.spec
mv ~/rpmbuild/RPMS/x86_64/*.rpm .
