import QtQuick 2.5

QtObject {
    readonly property string aboutApp: "About Interface";
    readonly property string addRemoveFriends: "Add/Remove Friends...";
    readonly property string addressBar: "Show Address Bar";
    readonly property string animations: "Animations...";
    readonly property string animDebugDrawAnimPose: "Debug Draw Animation";
    readonly property string animDebugDrawDefaultPose: "Debug Draw Default Pose";
    readonly property string animDebugDrawPosition: "Debug Draw Position";
    readonly property string antialiasing: "Antialiasing";
    readonly property string assetMigration: "ATP Asset Migration";
    readonly property string assetServer: "Asset Server";
    readonly property string atmosphere: "Atmosphere";
    readonly property string attachments: "Attachments...";
    readonly property string audioNetworkStats: "Audio Network Stats";
    readonly property string audioNoiseReduction: "Audio Noise Reduction";
    readonly property string audioScope: "Show Scope";
    readonly property string audioScopeFiftyFrames: "Fifty";
    readonly property string audioScopeFiveFrames: "Five";
    readonly property string audioScopeFrames: "Display Frames";
    readonly property string audioScopePause: "Pause Scope";
    readonly property string audioScopeTwentyFrames: "Twenty";
    readonly property string audioStatsShowInjectedStreams: "Audio Stats Show Injected Streams";
    readonly property string audioTools: "Show Level Meter";
    readonly property string autoMuteAudio: "Auto Mute Microphone";
    readonly property string avatarReceiveStats: "Show Receive Stats";
    readonly property string back: "Back";
    readonly property string bandwidthDetails: "Bandwidth Details";
    readonly property string binaryEyelidControl: "Binary Eyelid Control";
    readonly property string bookmarkLocation: "Bookmark Location";
    readonly property string bookmarks: "Bookmarks";
    readonly property string cachesSize: "RAM Caches Size";
    readonly property string calibrateCamera: "Calibrate Camera";
    readonly property string cameraEntityMode: "Entity Mode";
    readonly property string centerPlayerInView: "Center Player In View";
    readonly property string chat: "Chat...";
    readonly property string collisions: "Collisions";
    readonly property string connexion: "Activate 3D Connexion Devices";
    readonly property string console_: "Console...";
    readonly property string controlWithSpeech: "Control With Speech";
    readonly property string copyAddress: "Copy Address to Clipboard";
    readonly property string copyPath: "Copy Path to Clipboard";
    readonly property string coupleEyelids: "Couple Eyelids";
    readonly property string crashInterface: "Crash Interface";
    readonly property string debugAmbientOcclusion: "Debug Ambient Occlusion";
    readonly property string decreaseAvatarSize: "Decrease Avatar Size";
    readonly property string deleteBookmark: "Delete Bookmark...";
    readonly property string disableActivityLogger: "Disable Activity Logger";
    readonly property string disableEyelidAdjustment: "Disable Eyelid Adjustment";
    readonly property string disableLightEntities: "Disable Light Entities";
    readonly property string disableNackPackets: "Disable Entity NACK Packets";
    readonly property string diskCacheEditor: "Disk Cache Editor";
    readonly property string displayCrashOptions: "Display Crash Options";
    readonly property string displayHandTargets: "Show Hand Targets";
    readonly property string displayModelBounds: "Display Model Bounds";
    readonly property string displayModelTriangles: "Display Model Triangles";
    readonly property string displayModelElementChildProxies: "Display Model Element Children";
    readonly property string displayModelElementProxy: "Display Model Element Bounds";
    readonly property string displayDebugTimingDetails: "Display Timing Details";
    readonly property string dontDoPrecisionPicking: "Don't Do Precision Picking";
    readonly property string dontRenderEntitiesAsScene: "Don't Render Entities as Scene";
    readonly property string echoLocalAudio: "Echo Local Audio";
    readonly property string echoServerAudio: "Echo Server Audio";
    readonly property string enable3DTVMode: "Enable 3DTV Mode";
    readonly property string enableCharacterController: "Enable avatar collisions";
    readonly property string expandMyAvatarSimulateTiming: "Expand /myAvatar/simulation";
    readonly property string expandMyAvatarTiming: "Expand /myAvatar";
    readonly property string expandOtherAvatarTiming: "Expand /otherAvatar";
    readonly property string expandPaintGLTiming: "Expand /paintGL";
    readonly property string expandUpdateTiming: "Expand /update";
    readonly property string faceshift: "Faceshift";
    readonly property string firstPerson: "First Person";
    readonly property string fivePointCalibration: "5 Point Calibration";
    readonly property string fixGaze: "Fix Gaze (no saccade)";
    readonly property string forward: "Forward";
    readonly property string frameTimer: "Show Timer";
    readonly property string fullscreenMirror: "Mirror";
    readonly property string glowWhenSpeaking: "Glow When Speaking";
    readonly property string help: "Help...";
    readonly property string increaseAvatarSize: "Increase Avatar Size";
    readonly property string independentMode: "Independent Mode";
    readonly property string inputMenu: "Avatar>Input Devices";
    readonly property string keyboardMotorControl: "Enable Keyboard Motor Control";
    readonly property string leapMotionOnHMD: "Leap Motion on HMD";
    readonly property string loadScript: "Open and Run Script File...";
    readonly property string loadScriptURL: "Open and Run Script from URL...";
    readonly property string lodTools: "LOD Tools";
    readonly property string login: "Login";
    readonly property string log: "Log";
    readonly property string logExtraTimings: "Log Extra Timing Details";
    readonly property string lowVelocityFilter: "Low Velocity Filter";
    readonly property string meshVisible: "Draw Mesh";
    readonly property string miniMirror: "Mini Mirror";
    readonly property string muteAudio: "Mute Microphone";
    readonly property string muteEnvironment: "Mute Environment";
    readonly property string muteFaceTracking: "Mute Face Tracking";
    readonly property string namesAboveHeads: "Names Above Heads";
    readonly property string noFaceTracking: "None";
    readonly property string octreeStats: "Entity Statistics";
    readonly property string onePointCalibration: "1 Point Calibration";
    readonly property string onlyDisplayTopTen: "Only Display Top Ten";
    readonly property string outputMenu: "Display";
    readonly property string packageModel: "Package Model...";
    readonly property string pair: "Pair";
    readonly property string physicsShowOwned: "Highlight Simulation Ownership";
    readonly property string physicsShowHulls: "Draw Collision Hulls";
    readonly property string pipelineWarnings: "Log Render Pipeline Warnings";
    readonly property string preferences: "General...";
    readonly property string quit:  "Quit";
    readonly property string reloadAllScripts: "Reload All Scripts";
    readonly property string reloadContent: "Reload Content (Clears all caches)";
    readonly property string renderBoundingCollisionShapes: "Show Bounding Collision Shapes";
    readonly property string renderFocusIndicator: "Show Eye Focus";
    readonly property string renderLookAtTargets: "Show Look-at Targets";
    readonly property string renderLookAtVectors: "Show Look-at Vectors";
    readonly property string renderResolution: "Scale Resolution";
    readonly property string renderResolutionOne: "1";
    readonly property string renderResolutionTwoThird: "2/3";
    readonly property string renderResolutionHalf: "1/2";
    readonly property string renderResolutionThird: "1/3";
    readonly property string renderResolutionQuarter: "1/4";
    readonly property string renderAmbientLight: "Ambient Light";
    readonly property string renderAmbientLightGlobal: "Global";
    readonly property string renderAmbientLight0: "OLD_TOWN_SQUARE";
    readonly property string renderAmbientLight1: "GRACE_CATHEDRAL";
    readonly property string renderAmbientLight2: "EUCALYPTUS_GROVE";
    readonly property string renderAmbientLight3: "ST_PETERS_BASILICA";
    readonly property string renderAmbientLight4: "UFFIZI_GALLERY";
    readonly property string renderAmbientLight5: "GALILEOS_TOMB";
    readonly property string renderAmbientLight6: "VINE_STREET_KITCHEN";
    readonly property string renderAmbientLight7: "BREEZEWAY";
    readonly property string renderAmbientLight8: "CAMPUS_SUNSET";
    readonly property string renderAmbientLight9: "FUNSTON_BEACH_SUNSET";
    readonly property string resetAvatarSize: "Reset Avatar Size";
    readonly property string resetSensors: "Reset Sensors";
    readonly property string runningScripts: "Running Scripts...";
    readonly property string runTimingTests: "Run Timing Tests";
    readonly property string scriptEditor: "Script Editor...";
    readonly property string scriptedMotorControl: "Enable Scripted Motor Control";
    readonly property string showDSConnectTable: "Show Domain Connection Timing";
    readonly property string showBordersEntityNodes: "Show Entity Nodes";
    readonly property string showRealtimeEntityStats: "Show Realtime Entity Stats";
    readonly property string showWhosLookingAtMe: "Show Who's Looking at Me";
    readonly property string standingHMDSensorMode: "Standing HMD Sensor Mode";
    readonly property string simulateEyeTracking: "Simulate";
    readonly property string sMIEyeTracking: "SMI Eye Tracking";
    readonly property string stars: "Stars";
    readonly property string stats: "Stats";
    readonly property string stopAllScripts: "Stop All Scripts";
    readonly property string suppressShortTimings: "Suppress Timings Less than 10ms";
    readonly property string thirdPerson: "Third Person";
    readonly property string threePointCalibration: "3 Point Calibration";
    readonly property string throttleFPSIfNotFocus: "Throttle FPS If Not Focus"; // FIXME - this value duplicated in Basic2DWindowOpenGLDisplayPlugin.cpp
    readonly property string toolWindow: "Tool Window";
    readonly property string transmitterDrive: "Transmitter Drive";
    readonly property string turnWithHead: "Turn using Head";
    readonly property string useAudioForMouth: "Use Audio for Mouth";
    readonly property string useCamera: "Use Camera";
    readonly property string velocityFilter: "Velocity Filter";
    readonly property string visibleToEveryone: "Everyone";
    readonly property string visibleToFriends: "Friends";
    readonly property string visibleToNoOne: "No one";
    readonly property string worldAxes: "World Axes";
}

