# Docker file for hifi_base_ubuntu:1.1
FROM ubuntu:18.04
MAINTAINER DevOps Team (devops@highfidelity.io)

EXPOSE 40100 40101 40102
EXPOSE 40100/udp 40101/udp 40102/udp
EXPOSE 48000/udp 48001/udp 48002/udp 48003/udp 48004/udp 48005/udp 48006/udp

RUN apt-get update && apt-get install -y software-properties-common apt-utils curl
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15FF1AAE && add-apt-repository "deb http://debian.highfidelity.com stable main"
RUN echo UTC >/etc/timezone
# Installing via dependency causes interactive hang:
RUN apt-get -y install tzdata
RUN curl http://archive.ubuntu.com/ubuntu/pool/main/b/bison/libbison-dev_3.0.4.dfsg-1build1_amd64.deb >/tmp/libbison-dev.deb
RUN dpkg -i /tmp/libbison-dev.deb && rm /tmp/libbison-dev.deb
RUN apt-get update && apt-get -y --allow-unauthenticated install libglib2.0-0 libgl1-mesa-dev gdb python-pip build-essential \
    openssl libssl-dev libssl1.0.0 unzip flex bison gperf perl libsqlite3-dev \
    libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev libjpeg-dev \
    python libx11-dev libxext-dev libtbb2 hifiqt5.12.3 \
    ntp unzip libwww-perl libdatetime-perl make pkg-config libnss3 libxi6 \
    libxcursor1 libxcomposite1 libasound2 libxtst6 libxslt1.1 supervisor
# Additional packages for v1.1:
RUN apt-get -y --allow-unauthenticated install mesa-common-dev libegl1 libglvnd-dev \
    libdouble-conversion1 libpulse0
