<!--
//  Networking.vue
//
//  Created by Eugene :) on Nov. 24th, 2022.
//  Copyright 2022 Vircadia contributors.
//  Copyright 2022 DigiSomni LLC.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
-->

<template>
    <div class="q-pa-md">
        <!-- METAVERSE ACCOUNT SECTION/CARD -->
        <q-card class="my-card">
            <q-card-section>
                <div class="text-h5 text-center text-weight-bold">Your Metaverse Account</div>
                <div v-if="isUserConnected" class="text-overline text-positive text-center">Metaverse Account Connected</div>
                <div v-else class="text-overline text-negative text-center">Account Not Connected</div>

                <!-- METAVERSE CONNECT/DISCONNECT BUTTON -->
                <q-card-actions align="center">
                    <q-btn v-if="!isUserConnected" @click="onConnectAccount" class="q-mb-sm" padding="0.5em 2em" push color="positive" label="Connect Metaverse Account" />
                    <q-btn v-else @click="onConnectAccount" class="q-mb-sm" padding="0.5em 1.5em" push color="negative" label="Disconnect Account" />
                </q-card-actions>
                <!-- *END* METAVERSE CONNECT/DISCONNECT BUTTON *END* -->
                <q-separator />
                <!-- ADVANCED SETTINGS SECTION -->
                <q-expansion-item v-model="isAccountSettingsToggled" class="q-mt-md text-subtitle1" popup icon="settings" label="Advanced Settings">
                    <q-card>
                        <!-- access token section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="accessToken" label="Access Token"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is your OAuth access token to connect this domain-server with your Metaverse account. It can be generated by clicking the 'Connect Account' button above.<br/>
                            You can also go to the Security page of your account on your Metaverse Server and generate a token with the 'domains' scope and paste it here.</div>
                        </q-card-section>
                        <!-- domain ID section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="domainID" label="Domain ID"/>
                            <q-btn class="q-mt-xs" color="primary" label="new domain ID" />
                            <q-btn class="q-mt-xs q-ml-xs" color="primary" label="choose from my domains" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is your Metaverse domain ID. If you do not want your domain to be registered in the Metaverse you can leave this blank.</div>
                        </q-card-section>
                        <!-- local UDP port section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="localUDPPort" label="Local UDP Port"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is the local port your domain-server binds to for UDP connections.
                            Depending on your router, this may need to be changed to unique values for each domain-server in order to run multiple full automatic networking domain-servers in the same network.<br/>
                            You can use the value 0 to have the domain-server select a random port, which will help in preventing port collisions.</div>
                        </q-card-section>
                        <!-- enable packet verification section -->
                        <q-card-section>
                            <q-toggle v-model="isPacketVerificationEnabled" checked-icon="check" color="positive" label="Enable Packet Verification"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Enable secure checksums on communication that uses the Metaverse protocol. Increases security with possibly a small performance penalty</div>
                        </q-card-section>
                        <!-- enable metadata HTTP availability section -->
                        <q-card-section>
                            <q-toggle v-model="isHTTPMetadataEnabled" checked-icon="check" color="positive" label="Enable Metadata HTTP Availability"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Allows your domain's metadata to be accessible on the public internet via direct HTTP connection to the domain server</div>
                        </q-card-section>
                        <!-- metadata exporter HTTP port section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="localUDPPort" label="Metadata Exporter HTTP Port"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is the port where the Metaverse exporter accepts connections. It listens both on IPv4 and IPv6 and can be accessed remotely, so you should make sure to restrict access with a firewall as needed.</div>
                        </q-card-section>
                    </q-card>
                </q-expansion-item>
                <!-- *END* ADVANCED SETTINGS SECTION *END* -->
            </q-card-section>
        </q-card>
        <!-- *END* METAVERSE ACCOUNT SECTION/CARD *END* -->

        <!-- WebRTC Settings -->
        <q-card class="my-card q-mt-md">
            <q-card-section>
                <div class="text-h5 text-center text-weight-bold q-mb-sm">WebRTC</div>
                <q-separator />
                <!-- ADVANCED SETTINGS SECTION -->
                <q-expansion-item v-model="isWebRTCSettingsToggled" class="q-mt-md text-subtitle1" popup icon="settings" label="Advanced Settings">
                    <q-card>
                        <!-- enable WebRTC client connections section -->
                        <q-card-section>
                            <q-toggle v-model="isWebRTCConnectionsEnabled" checked-icon="check" color="positive" label="Enable WebRTC Client Connections"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Allow web clients to connect over WebRTC data channels.</div>
                        </q-card-section>
                        <!-- enable WebRTC WebSocket SSL section -->
                        <q-card-section>
                            <q-toggle v-model="isWebsocketSSLEnabled" checked-icon="check" color="positive" label="Enable WebRTC WebSocket SSL"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Use secure WebSocket (wss:// protocol) for WebRTC signaling channel. If "on", the key, cert, and CA files are expected to be in the local Vircadia app directory, in a /domain-server/ subdirectory with filenames vircadia-cert.key, vircadia-cert.crt, and vircadia-crt-ca.crt.</div>
                        </q-card-section>
                    </q-card>
                </q-expansion-item>
                <!-- *END* ADVANCED SETTINGS SECTION *END* -->
            </q-card-section>
        </q-card>
        <!-- *END* WebRTC Settings *END* -->

        <!-- WordPress OAuth2 Settings -->
        <q-card class="my-card q-mt-md">
            <q-card-section>
                <div class="text-h5 text-center text-weight-bold q-mb-sm">WordPress OAuth2</div>
                <q-separator />
                <!-- ADVANCED SETTINGS SECTION -->
                <q-expansion-item v-model="isWordPressSettingsToggled" class="q-mt-md text-subtitle1" popup icon="settings" label="WordPress OAuth2 Settings">
                    <q-card>
                        <!-- enable WebRTC client connections section -->
                        <q-card-section>
                            <q-toggle v-model="isOauth2AuthenticationEnabled" checked-icon="check" color="positive" label="Enable OAuth2 Authentication"
                                unchecked-icon="clear" />
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">Allow a WordPress-based (miniOrange) OAuth2 service to assign users to groups based on their role with the service.</div>
                        </q-card-section>
                        <!-- Authentication URL section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="authenticationURL" label="Authentication URL"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">The URL that the Interface will use to login via OAuth2.</div>
                        </q-card-section>
                        <!-- WordPress API URL Base section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="wordpressAPIURL" label="WordPress API URL Base"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">The URL base that the domain server will use to make WordPress API calls. Typically "https://oursite.com/wp-json/". However, if using non-pretty permalinks or otherwise get a 404 error then try "https://oursite.com/?rest_route=/".</div>
                        </q-card-section>
                        <!-- WordPress Plugin Client ID section -->
                        <q-card-section>
                            <q-input standout="bg-primary text-white" class="text-subtitle1" v-model="wordpressPluginID" label="WordPress Plugin Client ID"/>
                            <div class="q-ml-xs q-mt-xs text-caption text-grey-5">This is the client ID from the WordPress plugin configuration.</div>
                        </q-card-section>
                    </q-card>
                </q-expansion-item>
                <!-- *END* ADVANCED SETTINGS SECTION *END* -->
            </q-card-section>
        </q-card>
        <!-- *END* WordPress OAuth2 Settings *END* -->
    </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
    name: "Index",

    data () {
        return {
            isAccountSettingsToggled: ref(false),
            isWebRTCSettingsToggled: ref(false),
            isWordPressSettingsToggled: ref(false),
            // Metaverse Account section variables
            isUserConnected: false, // TODO: get connection status
            accessToken: "04b94c95-f93e-4f56-9973-9a9eef1440", // TODO: get access token
            domainID: 123456789, // TODO: get domain ID
            localUDPPort: 40102, // TODO: get local UDP port
            isPacketVerificationEnabled: false, // TODO: get packet verification setting state
            isHTTPMetadataEnabled: false, // TODO: get metadata HTTP availability setting state
            metadataExporterPort: 9704, // TODO: get metadata exporter HTTP port
            // WebRTC section variables
            isWebRTCConnectionsEnabled: false, // TODO: get web RTC client connections settings state
            isWebsocketSSLEnabled: false, // TODO: get webRTC webSocket SSL settings state
            // WordPress OAuth2 section variables
            isOauth2AuthenticationEnabled: false, // TODO: get OAuth2 Authentication settings state
            authenticationURL: "example.com", // TODO: get authentication URL
            wordpressAPIURL: "examplewordpressapi.com", // TODO: get wordpress API URL
            wordpressPluginID: "exampleID" // TODO: get wordpress plugin client ID
        };
    },
    methods: {
        onConnectAccount () {
            this.isUserConnected = !this.isUserConnected;
        },
        onNewDomainID () {
            console.log("new domain ID");
        },
        onChooseFromDomains () {
            console.log("choose from domains");
        }
    }
});
</script>
